name: publish

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  publish:
    permissions: {id-token: write}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: treeinfra/check-version@main
        with: {manager: cargo}

      - run: sh review.sh
      - run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
